server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # gateway lato Nginx (mima l'Ingress del cluster K8s)
    client_max_body_size 6m;
    location /api/menu   { proxy_pass http://menu-service:5001; }
    location /api/orders { proxy_pass http://order-service:5002; }

    location / { try_files $uri $uri/ /index.html; }
}
